### ISSUE TITLE
Build fails when project path contains a space

### ISSUE THREAD

**Issue by benface** [node-ffi-napi/weak-napi#24]
I believe the issue is in this package and not in `node-gyp`, because I have another package that needs `node-gyp` to be built in the same project and that one doesn't fail.

Here's the log:

```
> weak-napi@1.0.3 install /Users/benface/Desktop/Dev/Project with space/node_modules/weak-napi
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/weakref/src/weakref.o
clang: error: no such file or directory: 'with'
clang: error: no such file or directory: 'space/node_modules/node-addon-api'
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/benface/Desktop/Dev/Project with space/node_modules/weak-napi
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weak-napi@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak-napi@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Notice these lines in particular, which shows that *something* splits the path where there's a space:

```
clang: error: no such file or directory: 'with'
clang: error: no such file or directory: 'space/node_modules/node-addon-api'
```

Thank you!

**Comment by addaleax** [comment]
While I understand that that’s unfortunate, it’s not a bug directly related to this project. It’s most likely an issue in https://github.com/nodejs/node-gyp that would require a lot of effort to solve and that I cannot put in, sorry. You’ll run into this with a lot of software you try to compile in paths with spaces :/
